### ISSUE TITLE
Search page - search bar full styling support

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#147]
# Requirements

- [ ] Finish up styling the search bar 
    - [ ] change karat color to primary
    - [ ] fix font size and coloring
    - [ ] fix placeholders
- [ ] research using `vue-select` vs using native `<select>` element 
    - [ ] Look into safari styling not applying
    - [ ] is it worth the overhead?
    - [ ] does it support multi-select? 

# Dependencies

- None (Add any issue dependencies here)

**Comment by NabbeunNabi** [comment]
I have some questions about the ticket I was assigned. There are a lot of designs on figma so I do not know exactly which one I am supposed to follow for the TopNav/SearchBar part. Which should I follow?

**Comment by NabbeunNabi** [comment]
##  `<select>` Choices

### Make our own

- Pros
1.  Can be customizable to exactly what we want
2.  Possibly might not have trouble to adapt to our data
3.  More control over performance cost

- Cons
1.  Time consuming
2. Needs a lot of testing due to not being used by thousands of other developers

### Use `Vue Multi-Select`
[Link to Vue Multi-Select Page](https://vue-multiselect.js.org/)

- Pros
1.  Tested and proven to work
2.  Easy to add to our project
4.  Solid documentation

- Cons
1.  Might be tricky to adapt to our search query depending how we are handling it now
2. Could have extra performance costs that we cannot control

### My Research and Thoughts

Through my research I think it will be better to use the built in component. For an open source project it will be easier for developers who come in and out of the project to read the documentation and adjust the files when needed. I do not think that it will be too much if any extra performance cost. It also handles typing search and multi-select which is wonderful for a built in component. 

## Styling mismatch on Safari and Windows

- The select itself needs to use webkit to get rid of the default styling so it then takes our styling based on my research. So we need to change the original CSS file. [See MDN here](https://developer.mozilla.org/en-US/docs/Web/CSS/appearance)
- I think this is worth it for the scroll bar like I was talking about before as they appear differently as well as the `select` field to make the styling consistent across browsers.

**Comment by NabbeunNabi** [comment]
This is a rather old issue and as there is an issue for a redesign epic, I think we can close this for now and implement a different solution later. Also in one of the PRs there is a multiselect utility function built in.
