### ISSUE TITLE
Top Bar for moderation panel

### ISSUE THREAD

**Issue by Anissa3005** [ourjapanlife/findadoc-web#702]
# Problem
There seems to have been a mix-up regarding the creation of a top bar for the moderation panel. Although the issue was marked as done, the top bar is not visible.

We need to create a top bar for the moderation panel to enable searching through submissions, facilities, or healthcare professionals by name.

# Success
The moderation panel has a top bar with search functionality that allows users to search through submissions, facilities, or healthcare professionals.

![Image](https://github.com/user-attachments/assets/d4da1d42-1d92-462e-806a-bf12dcf94d42)

Figma:
https://www.figma.com/design/QXQxlw4jNFIhMxkKU7bbwq/Find-a-doc%2C-Japan?node-id=1611-23459

### Requirements

- [ ] Create the UI for the top bar in the `ModTopbar` component.
- [ ] Implement search functionality to filter through submissions, facilities, or healthcare professionals based on the list currently displayed.

**Comment by NabbeunNabi** [comment]
![image](https://github.com/user-attachments/assets/031958cb-6442-4694-95c9-712a6b04a417)
Correct @Anissa3005. The one for the forms are done and autofill IDs. But based off of the figma this is supposed to allow a search based on what is in the list item component and has no been done. I think it has been delayed due to it not being a vital part of functionality.

**Comment by NabbeunNabi** [comment]
@Anissa3005 @theyokohamalife This has been done now in https://github.com/ourjapanlife/findadoc-web/pull/739
