### ISSUE TITLE
Bug: update all component names to be multi-word compliant

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#86]
# Requirements 

- All vue component names should multiple words in the name
- ensure the app runs correctly with no JavaScript errors and routes work correctly 
- root path `/` without a route should go to home

**Comment by kappanjoe** [comment]
Happy to tackle this if it's still open to be assigned~

**Comment by kappanjoe** [comment]
To maintain the root path routing to home and to avoid complicating page routes in general, it seems that [the suggested workaround is to selectively turn off the multi-word rule](https://github.com/nuxt/eslint-config/issues/192#issuecomment-1005229219) with an override for `pages/**/*.vue` (and the eventual `layouts/*.vue`).

This also appears to already be built into [`nuxt/eslint-config`](https://github.com/nuxt/eslint-config), which we may wish to extend anyway since we're using Nuxt.

Would it be better to manually override the rule, or to extend eslint with the nuxt config file?
(And should this be split into a new issue?)

**Comment by theyokohamalife** [comment]
@kappanjoe So sorry but I went ahead and fixed this because we were getting a lot of warnings that were confusing new contributors! 🙇🏾‍♀️
